# **LOSS/COST FUNCTION IN DEEP LEARNING**

In [1]:
import numpy as np

y = np.array([1,1,0,0,1])
y_hat = np.array([0.30,0.7,1,0.5,0.899])


**MAE**

In [5]:
def Mean_abs_err(y,y_hat):
  tot_err = 0

  for y_,y_h in zip(y,y_hat):
    tot_err += abs(y_-y_h)
  print("Total error = ",tot_err)
  mae = tot_err/len(y)
  return mae

Mean_abs_err(y,y_hat)



Total error =  2.601


0.5202

In [8]:
np.mean(np.abs(y-y_hat))

0.5202

**LOG LOSS/BINARY_CROSS_ENTROPY**

In [9]:
epsilon = 1e-15

In [11]:
y_new = [max(i,epsilon) for i in y ]
y_new

[1, 1, 1e-15, 1e-15, 1]

In [15]:
y_new = [min(i,1-epsilon) for i in y_new]
y_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [16]:
y_new = np.array(y_new)

In [17]:
y_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [18]:
np.log(y)

<ipython-input-18-d0070684806c>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y)


array([  0.,   0., -inf, -inf,   0.])

In [19]:
np.log(y_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [22]:
def log_loss(y_hat,y_new):
  return -np.mean(y_hat*np.log(y_new)+(1-y_hat)*np.log(1-y_new))

In [23]:
log_loss(y_hat,y_new)

17.967247551986667

In [25]:
def Mean_Square_err(y,y_hat):
  tot_err = 0

  for y_,y_h in zip(y,y_hat):
    tot_err += (y_-y_h)**2
  print("Total error = ",tot_err)
  mse = tot_err/len(y)
  return mse

Mean_Square_err(y,y_hat)



Total error =  1.840201


0.3680402